### ISSUE TITLE
can't run grunt without --force

### ISSUE THREAD

**Issue by choweiyuan** [mronemous/ghost-theme-techno#16]
Running "sass:compile" (sass) task
OptionParser::InvalidOption: invalid option: --banner=/*! Techno - v1.0.0 - 2015-02-08
  Use --trace for backtrace.
Warning: Exited with error code 1 Used --force, continuing.

if I run with --force it works fine

I suspect this has to do with the recent changes at https://github.com/gruntjs/grunt-contrib-sass
2015-02-06   v0.9.0   Remove banner option. Allow using --force to ignore compile errors. Increase concurrency count from 2 to 4. Improve Windows support.

Was wondering if the following (Gruntfile.js) should be tweaked to cope with the latest changes, or should I always run with --force

    sass: {
      compile: {
        options: {
          style: 'compact',
          banner: '<%= banner %>'
        },
        files: {
          'assets/css/compiled_sass.css': 'assets/sass/style.scss'
        }
      }
    },

Thanks

**Comment by mronemous** [comment]
The project is still pointing to ~0.7.3  in the package.json so this change should not affect the project.  Did you customize any of the scss files or change the package.json?

**Comment by choweiyuan** [comment]
Yea I was fiddling quite a few stuff, I've decided to start from scratch that and that error seems to be gone now. Sorry!

On a different note, I got this error
```
Running "sass:compile" (sass) task
Error: Invalid CSS after "": expected keyframes selector (e.g. 10%), was "0"
        on line 72 of assets/sass/partials/_navigation.scss
        from line 2 of assets/sass/default.scss
        from line 7 of assets/sass/style.scss
  Use --trace for backtrace.
```

Fixed it by adding a percent to 0 at _navigation.scss
```
@-webkit-keyframes pulse {
  // 0 {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@-moz-keyframes pulse {
  // 0 {
  0% {
    -moz-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -moz-transform: scale(1.2);
    transform: scale(1.2);
  }
  100% {
    -moz-transform: scale(1);
    transform: scale(1);
  }
}
```

**Comment by mronemous** [comment]
Thanks.  I pushed this change.  I hope you enjoy the theme, and let me know if you run into anything else.
